### PR TITLE
Fixes #103, logo change

### LINKED ISSUE #103: Replace Project Hope logo w/ CfB logo
Self-explanatory.

### PR DESCRIPTION
**Pull request by WillMcIntosh**
I took the logo image off of the cfb twitter page because it was the highest quality then appended the text from codeforboston.org. Colors changed to match the current site theme.

### CODE REVIEW

**Comment by lianilychee** [comment]
@WillMcIntosh could you include a screenshot please?  Thanks!

**Comment by WillMcIntosh** [comment]
@knod oops! good catch. I think while I'm at it I want to change the menubar logo to be side by side instead of stacked. It's less obtrusive this way, I think. 
I'll leave the big one in the intro page stacked because it looks kinda weird side by side. (see screen fetches)

screenfetch-2017-10-19_13-25-45
screenfetch-2017-10-19_13-26-16
screenfetch-2017-10-19_13-29-23

**Comment by WillMcIntosh** [comment]
@lianilychee here's another screen shot of the stacked logo as the big one on the intro page. Thoughts? 
screenfetch-2017-10-19_13-34-33

**Comment by knod** [comment]
I kinda like side-by side better for all things. Feels more readable.

**Comment by WillMcIntosh** [comment]
Thoughts on this homepage? 
screenfetch-2017-10-19_14-02-23

**Comment by lianilychee** [comment]
The text "A CfA Brigade" is a little faint; I can edit and PR to your fork.  Otherwise, looks good!

**Comment by WillMcIntosh** [comment]
that sounds good if you want to take a crack at it @lianilychee and I can merge your changes as soon as you send them.

**Comment by lianilychee** [comment]
@WillMcIntosh [new image here](https://vectr.com/lianilychee/c1ontKFPf6.svg?width=400&height=150&select=c1ontKFPf6page0)  I know it looks like whitespace, but you can right-click + save-as.

1.  I vectorized the image, so it's not grainy and now scalable.  Let me know if SVG format doesn't work out.
2.  I made the "A CfA Brigade" text bolder.

**Comment by knod** [comment]
What we could do is merge this and then let @lianilychee make changes to the merged result.

**Pull request merged**
