### PR TITLE
Specifies node version

### PR DESCRIPTION
**Pull request by alvincrespo**
## Changes

- Adds a `.node-version` file to ensure consistent node version among devs

## Developer Experience

If you're using [nvm](https://github.com/creationix/nvm), you can run:

```
nvm use $(cat .node-version)
```

This will set the node version to be used with this project.

If you do not have this version installed, you can run:

```
nvm install $(cat .node-version)
```

### CODE REVIEW

**Comment by alvincrespo** [comment]
Not sure if this is the version of node we want to stabilize on - but thought I'd create a PR 😄

**Review by ethanbb — COMMENTED** [review]
I think it might make sense to use the LTS version of Node instead of the latest, unless there's something we need in Node 10. No strong opinion from me though.

**Comment by knod** [comment]
Thanks for the PR, @alvincrespo , it's probably a good idea! I agree about the latest stable version as opposed to just the latest version.

Also, just curious, but with a .node-version file present, isn't the command just `nvm use`? I've never seen the `$(...)` syntax before, so maybe I'm misreading something.

**Comment by knod** [comment]
By latest stable version, I do mean an actual version number, not just a general 'LTS' command. Is that what you meant, @ethanbb ?

**Comment by ethanbb** [comment]
Yup.

**Comment by turnerhayes** [comment]
We might consider using an [.nvmrc](https://github.com/creationix/nvm#nvmrc) file so that we don't have to `cat` files

**Comment by knod** [comment]
That looks like an attractive option.

**Comment by turnerhayes** [comment]
Can we close this due to #979 ?

**Comment by knod** [comment]
Closed due to #979.

**Pull request closed without merging**
