### PR TITLE
ManagedNumberField cleaning up variable name and function call

### PR DESCRIPTION
**Pull request by snyderc**
When I was writing unit tests, I noticed a couple of seemingly redundant/unnecessary bits of code in the ManagedNumberField.

The handleBlur function appeared to first call this.props.onBlur -- which would be calling itself, right? Removing the call didn't seem to affect app functionality. When I made this change, I also cleaned up a line of code in the test that's no longer needed if this change is made.

handleFocus takes in inputProps but doesn't use it, so I suggest removing the parameter.

### CODE REVIEW

**Comment by shp54** [comment]
`inputProps` can be removed, but `this.props.onBlur` allows a developer to add a custom function to be called whenever the input blurs. I'm not super sure of the utility, but I'd recommend making it optional rather than removing it (only running that method if it exists)

**Comment by knod** [comment]
Actually, we're really not using `this.props.onBlur`. If you look in `<CashFlowRow>`, it just returns `true`. I'm not sure why that happened. Maybe we were planning to store values that way, but it became moot. I think we can delete it now and add it later if needed.

As for `inputProps`, they're in a lot of places where they don't need to be. I was the main person putting that in and it was before I understood the React ecosystem at all. I think it'd be great to remove it wherever it isn't needed, though it would have to be a careful extraction because sometimes it is actually used. If no one wants to take on that burden, which I'd completely understand, I can work on it at some point.

Thanks for cleaning this stuff up!

**Comment by knod** [comment]
@snyderc : Are you up for resolving the conflicts here? I think you just have to merge dev.

**Comment by knod** [comment]
See this for desired behavior: https://github.com/codeforboston/cliff-effects/issues/630

**Comment by knod** [comment]
I think I just rememberd our old use for `inputProps` - we were using `inputProps.value` before we found we could use `evnt.target.value`.

**Comment by knod** [comment]
You could probably destroy the sources of the `onBlur` as well, btw, if you're up for it.

**Comment by snyderc** [comment]
Resolved merge conflicts, and removed onBlur from CashFlowRow, with today's commits. Should be all ready unless there are other questions.

**Pull request merged**
