### PR TITLE
Puts errors above the invalid question answer. Fixes #909

### LINKED ISSUE #909: Put error above input
For those inputs that can show an error, use the `<Surrounder>` to put the error above the right input/row.

Hopefully this will help move towards a mobile-friendly experience.

### PR DESCRIPTION
**Pull request by knod**
Maybe help prep for mobile a bit.

### CODE REVIEW

**Review by dylanesque — COMMENTED** [review]
Why was the last change I made to VisitPage.js inline styles reverted to it's original form here?

**Comment by knod** [comment]
@dylanesque : I have no idea. Maybe something that'll get worked out when the merge conflicts are fixed... What line(s) is/are changed back?

**Comment by knod** [comment]
If it's the stuff for the `StepBar`, then it's a merge conflict thing.

**Comment by dylanesque** [comment]
> @dylanesque : I have no idea. Maybe something that'll get worked out when the merge conflicts are fixed... What line(s) is/are changed back?

The inline style I refactored out of VisitPage.js was put to its previous place. If there's a merge, that's one thing, it just seemed off to have a change approved in another PR and reverted here.

**Comment by knod** [comment]
@dylanesque : How does the code look now that the merge conflicts are resolved?

**Comment by dylanesque** [comment]
> @dylanesque : How does the code look now that the merge conflicts are resolved?

Almost there, just put the ```/* VisitPage.js styles */	
 #form-nav, .current-step-component {	
  padding: 14px 0;	
}``` back in index.css and I can approve this, losing that change was the only issue I had with this PR.

**Comment by knod** [comment]
@dylanesque : Nice catch! Thanks!

**Review by dylanesque — APPROVED** [review]

**Pull request merged**
