### PR TITLE
Changes var name to reflect purpose (not terms of service)

### PR DESCRIPTION
**Pull request by knod**

### CODE REVIEW

**Review by dylanesque — CHANGES_REQUESTED** [review]
I think this warrants a consensus discussion, the new var name strikes me as counter-intuituive and confusing.

**Comment by knod** [comment]
Yeah, there's probably a better name. It just needs a different one.

**Comment by knod** [comment]
`distrustConfirmed`?

**Comment by knod** [comment]
If you're working on the code, you should be aware that a user should not trust the site.

**Comment by dylanesque** [comment]
> `distrustConfirmed`?

Yeah, that's much better IMHO

**Comment by knod** [comment]
Updated the name and renames the toggling function too.

**Review by dylanesque — APPROVED** [review]

**Pull request merged**
