### PR TITLE
Increase timeout for Jest on big regression test

### PR DESCRIPTION
**Pull request by ethanbb**
Making this PR now so I can see how this works in Travis.

### CODE REVIEW

**Comment by knod** [comment]
I think this was the kind of thing I was talking about, but I'm no longer sure: https://travis-ci.org/codeforboston/cliff-effects/builds/430572084

**Comment by knod** [comment]
If I recall correctly now, it wasn't about a time limit for the whole test suite, it was about having too long a pause between responses sent to Travis.

**Comment by jlangevin** [comment]
Could this be the issue.  I pushed some code earlier and a test unrelated to my work failed.

https://api.travis-ci.org/v3/job/430648409/log.txt

"getSNAPBenefits() matches saved results

Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."

**Comment by ethanbb** [comment]
@jlangevin Yeah, that's the issue that I can replicate with a sleep call (if I don't override the timeout interval like I'm doing here). I think the best way to address when this happens is to identify tests that take longer and allow more time for just those tests (the 3rd argument to `test` is timeout in ms). We can't override the global timeout interval without ejecting from create-react-app, it seems.

**Comment by ethanbb** [comment]
OK, I just looked at it too and I see what you're talking about - the test cases in `test/programs/federal/snap/test-cases.txt`, right? I think this is related to what Michelle was telling me yesterday about generating tests via `setupTests.js`. @knod, were you involved with writing this test, and if so (or not) do you think we ought to keep it this long, or break it up in some way?

**Comment by ethanbb** [comment]
@knod Interesting. I'm confused about what happened with that build - there doesn't seem to be any output at all from the test script. Did that just happen randomly?

No output for 10 minutes seems like a pretty reasonable fail condition, but if that's also happened when the tests were actually running correctly, we should change it.

**Comment by knod** [comment]
It may just be something that happens with Travis sometimes - maybe a connection issue - but I'm not sure. Giving Travis a longer time may help or it may not. Still, this branch has a fix for the Jest stuff, so maybe we can merge it anyway and have that fix available. It's shame we can't make it a global change :/

**Comment by knod** [comment]
Let us know when it's not WIP anymore and we can do the approval thing!

**Comment by ethanbb** [comment]
Hey just to be clear, this shouldn't be merged since the only change I made was artificially increase the time required for a test and tell Jest to allow a longer time for it. The real fix would be to find the tests that actually take a long time (like that SNAP regression test) and increase the time allowed for them. And we should write down how to do that in the future since it'll probably happen again with new tests.

**Comment by knod** [comment]
So you mean chunk it like @jlangevin suggested?

**Comment by ethanbb** [comment]
We could do that, or if it's easier in the short term and it's causing issues with PRs now, we could increase the time limit and put in an issue to refactor it later.

**Comment by knod** [comment]
My vote is for the latter, since there's so much to do, but it might be a quick fix and I won't object if folks want to look into it. @ethanbb , do you want to take a look to see if it can be quick?

**Comment by ethanbb** [comment]
OK, I can take a little time looking into how easy it would be to refactor the test before just giving it extra time.

**Comment by ethanbb** [comment]
No longer WIP

**Review by wacii — APPROVED** [review]
Seeing jasmine referenced here is a little jarring, but it looks good. I forgot you could pass a timeout as a third argument.

**Comment by turnerhayes** [comment]
I'm curious if you tried running tests with `--runInBand` passed? I had issues with Jest tests timing out with a project of mine in Travis, and passing that flag (or `-i` for short) resolved it. Don't know if that's the issue here, but figured I'd bring it up.

**Comment by knod** [comment]
May be worth some research!

**Pull request merged**
