### PR TITLE
Switches to 'consistent' bracket style. #507. No fixes needed.

### PR DESCRIPTION
**Pull request by knod**
As per discussion. Can't find the issue for it. Anyone remember one?

### CODE REVIEW

**Comment by ethanbb** [comment]
I think we just talked about it on Slack without making an issue.

**Comment by knod** [comment]
I thought it allowed
```js
var a = [ 1, 2 ];
// and _also_
var a = [
  1,
  2
];
```

Which is a thing I thought someone wanted and made sense to me.

**Comment by ethanbb** [comment]
Oh whoops, you got rid of `array-element-newline` - didn't see that. That's good. My first comment was about changing `array-bracket-newline`, but that's not as big a deal as getting rid of the other one.

**Comment by knod** [comment]
Hmm, thought I'd read over those thoroughly. Maybe I should re-read instead of trusting my past self.

**Comment by knod** [comment]
So my understanding was that we wanted both to be able to put array/bracket items on one line and, at other times, to choose to put the array/bracket items on multiple lines. That is, we wouldn't require non-empty brackets to have new lines in them. I think that's what `"consistent"` allows: https://eslint.org/docs/rules/array-bracket-newline

**Comment by ethanbb** [comment]
As I understand it, `array-bracket-newline` is _just_ about newlines directly after opening brackets and directly before closing brackets. Whereas `array-element-newline` deals with newlines _between_ array elements.

**Comment by knod** [comment]
Right, but we don't want to require new lines in brackets, right? We just want them there when elements are on new lines, otherwise we want everything to be on the same line.

**Comment by knod** [comment]
Hmm, I'm rethinking this whole thing. This may not be what we were looking for.

**Comment by knod** [comment]
With `"array-bracket-newline": ..."always"`, though, I don't think we can have the two things I showed.

**Comment by knod** [comment]
Ok, new plan. We'll require new lines for elements and brackets stays the same. New PR coming up.

**Pull request closed without merging**
