### PR TITLE
Fixes #868 reset text gone. Also messes with wording T_T

### LINKED ISSUE #868: Last section 'New Client' text has disappeared.
### Replicate:
1. Go to Predictions section
2. Click 'New Client'

### Result I'd Expect:
- See a modal with text in it.

### Actual Result:
- See a modal without text in it, though it has buttons.

### Environment:
App version or commit id at the time: ebadf95e8cc17c482d8e1d803d59786237f12833

### Other Notes
I've got it, but I messed with the wording too. Goramit. Maybe I can pull that out of there.

### PR DESCRIPTION
**Pull request by knod**

### CODE REVIEW

**Comment by knod** [comment]
My local feedback prompt snapshot test is working... no idea what's going on.

**Comment by knod** [comment]
Fixed *shrug*

**Review by dylanesque — CHANGES_REQUESTED** [review]
Just about there, save for the mixing of concatenation operators and template strings in FeedbackPrompt.js.

**Comment by knod** [comment]
@dylanesque : Thanks! If you attach your comment to a line in the code, it'll show as resolved when that line has been edited.

**Comment by dylanesque** [comment]
> @dylanesque : Thanks! If you attach your comment to a line in the code, it'll show as resolved when that line has been edited.

That's definitely better, but before I approve, did you want those statements on separate lines like they were in the previous iteration of that code? I'm wondering if it was formatted that way to get that secondary benefit of multi-line strings from template literals.

**Comment by knod** [comment]
@dylanesque : No, they weren't supposed to be visually broken up into separate lines in the site.

**Review by dylanesque — APPROVED** [review]

**Comment by dylanesque** [comment]
> @dylanesque : No, they weren't supposed to be visually broken up into separate lines in the site.

K, just wanted to confirm that wasn't your intention before approving.

**Pull request merged**
