### PR TITLE
More robust styles and structure for left-fixed buttons

### PR DESCRIPTION
**Pull request by knod**

### CODE REVIEW

**Comment by knod** [comment]
Also prep for combining the reset buttons into one reset button

**Review by dylanesque — DISMISSED** [review]
Almost there, the render method of VisitPage.js would be a lot more readable with any and all state and props items destructured.

**Comment by knod** [comment]
@dylanesque : I do love that idea! Is there a reason it's appropriate as part of this PR? We try to keep PRs focused on one task at a time.

**Comment by knod** [comment]
@dylanesque : Just pinging you again on this question.

**Comment by knod** [comment]
The change requested wasn't related to the PR, no other changes have been requested, and this PR has been sitting here for a while, so it's being merged.

**Pull request merged**
