### PR TITLE
Lint config to add line at end of file

### PR DESCRIPTION
**Pull request by knod**

### CODE REVIEW

**Comment by knod** [comment]
@wacii: Ah, got it. Assumed it was a typo. I'll look into their string versions.

**Comment by wacii** [comment]
0 = "off", 1 = "warn", 2 = "error"

**Comment by knod** [comment]
What's the deal with the strings in arrays vs. just strings, btw? Can they all be in arrays?

**Comment by knod** [comment]
I'll make a different PR with this config stuff. I was planning on doing some cleaning in here anyway.

**Comment by wacii** [comment]
I think the default way to provide the arguments is with an array. The just-string way is a shortcut for when you only have the one argument.

**Pull request merged**
