### PR TITLE
README rewrite

### PR DESCRIPTION
**Pull request by lianilychee**
I have [rewritten the README](https://github.com/codeforboston/cliff-effects/tree/onboarding-streamline) as part of the effort to improve onboarding.  I intend for the README to serve as any newcomer's first written introduction to the project, and for design / engineering folks to split off accordingly.  @WillMcIntosh has already screened for comprehensiveness and clarity.  

@carpeliam @knod @zzyyfff , would appreciate feedback on:

- general response?
- classification of work from Design and Tech --> Eligibility parsing, Data viz, UX.  These are what I mean by topical classification.

### CODE REVIEW

**Comment by knod** [comment]
First off, those categories/topics sound excellent. Great articulation of the state of the work. I also think it'll be great to remove the copy of the React explanations at this point.

Possible improvements (most of this stuff would have applied to the old readme too):
- A link to the React page that contained those details (current version has them at 'Below you will find some information... guide here.').
- The bit about the node version should also include that versions at or above 5.0 are preferred. This is based on some recent discoveries about the differences between the old and new versions.
- I'd still like to discuss people forking the repo as opposed to cloning straight from the code-for-boston repo.
- We now do not want people to `git checkout master`, we want them to be on the 'dev' branch.
- We probably didn't discuss this, but `npm run build` is not actually needed. It doesn't currently do anything. In future we may wan to have people run tests on their build, but currently that isn't the case. Currently `npm run deploy` will build and deploy.
- Do we want `npm run deploy` to be common knowledge? I believe there are currently no restrictions on who can deploy, so people who misunderstand what that does may end up pushing things live that they don't intend to.
- Do we want anyone working on this who isn't able to work with git, or with code in general? I think that those kinds of people could still be useful resources, but maybe I just don't have enough field experience to see that they wouldn't. If we do still want those people, then the tip about setting up their environment may not be ideal. It would probably dissuade people without technical know-how.

Less technical:
- An explanation that it's not really the case workers' job to know these calculations - that it's not that they're not doing their job, it's that that in particular is not their job. I don't know quite how to articulate it well.

Sorry to pile on a bunch of stuff. I really appreciate you working on the readme. It was great as a starting point and it's great to see it progressing to fit the current state of the project. It's already looking much more clear and clarifying about where we're at.

**Comment by lianilychee** [comment]
Thanks for your notes, @knod !  You're right that it's a lot of points, but they're necessary!  I truly don't mind.

I have just:

- Added an addendum about us amplifying case workers' impact, not taking over their jobs
- Added the note about Node versions.
- Added a link to the Create React App README, right under the Git Tutorial.  Thoughts on location?
- Modified the clone command with fork.  I spoke with Liam last Tuesday, and he walked me through the pros / cons each.

> We now do not want people to git checkout master, we want them to be on the 'dev' branch.

I changed `master` to `dev`.  I should probably add in a line or two re: it doesn't matter what branch someone is working on in their own fork.  (Like, it doesn't have to be `dev` on their own fork.)

> We probably didn't discuss this, but npm run build is not actually needed. It doesn't currently do anything. In future we may wan to have people run tests on their build, but currently that isn't the case. Currently `npm run deploy` will build and deploy.  Do we want `npm run deploy` to be common knowledge? I believe there are currently no restrictions on who can deploy, so people who misunderstand what that does may end up pushing things live that they don't intend to.

Hmm.  True, that we don't want `codeforboston/cliff-effects` changing willy nilly.  But it doesn't matter what people deploy on their own forks, right?  I can clarify that, too.

> Do we want anyone working on this who isn't able to work with git, or with code in general? I think that those kinds of people could still be useful resources, but maybe I just don't have enough field experience to see that they wouldn't. If we do still want those people, then the tip about setting up their environment may not be ideal. It would probably dissuade people without technical know-how.

I can put in a line right under the Environment Setup header stating that the section is for devs only?

**Comment by knod** [comment]
Some awesome changes!

> ... link to the Create React App README... Thoughts on location?

The location looks good, but thinking about it now, it might be more useful to have 'We're building this project with React (link: https://facebook.github.io/react/docs/react-api.html). It was bootstrapped with  Create React App (link to the table of contents instead: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md). Sorry that didn't occur to me sooner and that I wasn't clear about the table of contents.

> Added an addendum about us amplifying case workers' impact, not taking over their jobs

My aim was not so much to reassure people that we weren't taking over their jobs. It was more to explain that this isn't their job. I.e. we're not doing this because the Project Hope case managers aren't handling it, we're doing it because this isn't within their purview and yet could be a thing that would really help them.

> fork

I might jump in and do some work on the description of forking. It might be clear enough as it is, but I can think of a couple ways that would have made it more clear to me when I was just starting out.

> it doesn't matter what branch someone is working on in their own fork

This is true! Though unless we put it carefully, it may be more confusing than helpful. Also, maybe there isn't a good way to put this into the README, but a workflow that is a bit more involved can save a lot of pain. This is from my own experiences, so maybe someone else has different input. It involves doing your best to not change anything on your own dev branch at all, only on branches made from 'dev'. Maybe we can talk about it in more detail face to face.

> it doesn't matter what people deploy on their own forks

This may or may not be true. I think Alec is coming tonight and he might have a clearer idea. I haven't had a chance to sit down and learn it in-depth, but it's possible that the command always deploys to the code-for-boston repo.

**Comment by knod** [comment]
> I can put in a line right under the Environment Setup header stating that the section is for devs only?

Sorry, didn't see this. Yeah, something like that sounds like it'd do the job. One possible change, though, maybe your intention for a final version already has this in mind - I'm not sure what the common understanding of a 'dev' - whether that's always assumed to be a coder, but if not 'code devs' might be a more clear way of putting it.

**Comment by knod** [comment]
Also, to put our words into ink:

`npm run deploy` will currently deploy to the code-for-boston repo, no matter whose fork it's on or where it's being called from. To those who are curious, there's further discussion of possible solutions in #60.

**Comment by knod** [comment]
Regardless, it looks like a good start and we can improve on it later if needed, so I'm going to merge it.

**Pull request merged**
