### PR TITLE
Vietnamese translation - #513, #500

### PR DESCRIPTION
**Pull request by hmtranae**
Vietnamese translation of en.js; not familiar with JSON format but all of the objects keys are surrounded with single quotes which is not the case in en.js. Would this cause a problem?

### CODE REVIEW

**Comment by knod** [comment]
It's strange that it copied that way, but it won't break anything. I'll have to check out the google en.js doc.

**Comment by knod** [comment]
Hmm, forgot we had the localization checker. There seem to be a couple other things amiss, but I think we can take care of those too just fine. Do what you will!

**Comment by knod** [comment]
Ha! I think it's something wrong with en.js! Eh, let's go with this and we'll see what we see when everything _else_ is up to snuff.

**Comment by knod** [comment]
It looks like you've got it covered, thanks! A PR maker needs one approval to be able to merge, so after the tests pass, feel free to merge anytime!

**Comment by hmtranae** [comment]
Okay great, thanks!

**Pull request merged**
