### PR TITLE
Start of rake tests, #315

### PR DESCRIPTION
**Pull request by knod**
This is the logic testing I was talking about. I know folks aren't fans, but gotta do something within the coming week, and this allows for fully examining edge case behavior. We'll see how long the tests take to run as we build up iterations.

### CODE REVIEW

**Comment by wacii** [comment]
@knod Just to be sure. Is this basically what you were trying to write?

```js
const expected = {
  0: 192,
  100: 192,
  1000: 42.9
};

Object.keys(expected).forEach(earned => {
  const client = cloneDeep(CLIENT_DEFAULTS);
  client.current.earned = earned;
  it(`with household of __, current earnings of ${earned}`, () => {
    expect(getSNAPBenefits(client, 'current')).toBeCloseTo(expected[earned], 4);
  });
});
```

**Comment by knod** [comment]
@wacii: No, actually, not quite. That doesn't account for further permutations. There will be a different result for a household with that earned income that has one member vs. one that has 8 members. I'm just showing the first of many iterators. If it would help, I'll add another one.

**Comment by wacii** [comment]
Ah, I see. So you will be looking at combinations of number of members and earned income. The underscores in the test case names make sense now.

**Comment by knod** [comment]
Another layer has been added, so maybe it's a bit easier to see how this will grow. It adds a bit of utility testing.

**Comment by knod** [comment]
Branches still exist on my repo, but wacii is taking the functionality shown in those to try to pre-build test those test cases instead of generating them at run-time.

**Pull request closed without merging**
